export const homeObjOne = {
  primary: true,
  lightBg: false,
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "Developer",
  headline: "Build amazing react projects",
  description: "I'm a front-end developer based in Assam",
  buttonLabel: "Get Started",
  imgStart: "",
  img: require("../../images/svg-3.svg").default,
  alt: "Credit Card",
  start: "",
};
export const homeObjTwo = {
  primary: true,
  lightBg: false,
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "Developer",
  headline: "Hi I'm Swaraj",
  description: "I'm a front-end developer based in Assam",
  buttonLabel: "Get Started",
  imgStart: "start",
  img: require("../../images/svg-8.svg").default,
  alt: "Credit Card",
  start: "true",
};
export const homeObjThree = {
  primary: true,
  lightBg: false,
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "Developer",
  headline: "Hi I'm Swaraj",
  description: "I'm a front-end developer based in Assam",
  buttonLabel: "Get Started",
  imgStart: "",
  img: require("../../images/svg-5.svg").default,
  alt: "Credit Card",
  start: "",
};
export const homeObjFour = {
  primary: true,
  lightBg: false,
  lightTopLine: true,
  lightText: true,
  lightTextDesc: true,
  topLine: "Developer",
  headline: "Hi I'm Swaraj",
  description: "I'm a front-end developer based in Assam",
  buttonLabel: "Get Started",
  imgStart: "start",
  img: require("../../images/svg-7.svg").default,
  alt: "Credit Card",
  start: "true",
};
